apiVersion: v1
kind: PersistentVolume
metadata:
  # The name of our manual Persistent Volume
  name: test-manual-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    # This should match the physical size of your volume in AWS
    storage: 2Gi
  # We still use the CSI driver to handle the mounting!
  csi:
    driver: ebs.csi.aws.com
    # Here is where we hardcode the exact physical AWS Volume ID
    volumeHandle: vol-09c5d16af7b5ed2cc
  # Retain means if we delete the PVC, do NOT delete the physical drive in AWS
  persistentVolumeReclaimPolicy: Retain
