apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-auto
# The CORRECT provisioner name for the AWS EBS CSI Driver
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
