# The API version for Kubernetes Networking
apiVersion: networking.k8s.io/v1

# An Ingress is a set of routing rules that map outside internet traffic to our internal services
kind: Ingress

metadata:
  # The name of our ALB routing rules
  name: alb-ingress
  # The ALB must be in the same namespace as the Traefik service
  namespace: traefik
  annotations:
    # Tell Kubernetes to use the AWS ALB Controller we are going to install
    kubernetes.io/ingress.class: alb
    # We want this load balancer to be accessible from the public internet
    alb.ingress.kubernetes.io/scheme: internet-facing
    # IP mode routes directly to the Traefik Pod IPs for maximum performance
    alb.ingress.kubernetes.io/target-type: ip
    # Tell the ALB that a 404 from Traefik is actually healthy (since Traefik returns 404 for unknown health-check hosts)
    alb.ingress.kubernetes.io/success-codes: '200,404'
    
    # Listen on both HTTP and HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # Force automatically redirect HTTP to HTTPS
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    
    # TODO: We will paste your AWS Certificate Manager (ACM) SSL Certificate ARN here!
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-north-1:990151164914:certificate/f79bdd39-c116-43ec-b754-d94acc8a3ea6"

spec:
  rules:
    - host: thechamp.app
      http:
        paths:
          # Match all traffic hitting the root path (/)
          - path: /
            pathType: Prefix
            backend:
              service:
                # Route the matched traffic to Traefik!
                name: traefik
                port:
                  number: 80
