### e:/K8s/ansible/group_vars/all.yml
kubernetes_version: "1.30"
kubernetes_version_full: "1.30.0"
pod_network_cidr: "192.168.0.0/16"
calico_version: "v3.27.0"
containerd_version: "latest"
ebs_csi_driver_chart_version: "2.28.0"
traefik_chart_version: "26.0.0"
aws_region: "eu-north-1"
cluster_name: "k8s-kubeadm"
domain: "thechamp.app"
storage_class_name: "ebs-sc"
traefik_namespace: "traefik"
traefik_image_tag: "v3.0"
kubeconfig_path: "/home/ubuntu/.kube/config"
